spring:
  application:
    name: supplier-service





  flyway:
    url: ${DB_JDBC_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5671
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: true

  main:
    web-application-type: reactive

  jackson:
    serialization:
      indent-output: true

postgresql:
  host: ${DB_R2DBC_URL}
  port: 5432
  database: postgres
  schema: public
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  ssl: allow

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.flywaydb: DEBUG

catalog:
  url: http://arka-alb-1425980331.us-east-1.elb.amazonaws.com

security:
  jwt:
    secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
